{% set name = "ttach" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ttach-{{ version }}.tar.gz
  sha256: 120c4dd881feb0e9c8dd63b154f2655891c3e20689b68a94d162bfd5557bcb48

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pytorch >=1.4.0

test:
  imports:
    - ttach
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/qubvel/ttach
  summary: Images test time augmentation with PyTorch.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/qubvel/ttach
  dev_url: https://github.com/qubvel/ttach

extra:
  recipe-maintainers:
    - sugatoray
